name: pipe_x
description: A lightweight, reactive state management library for Flutter with fine-grained reactivity and minimal boilerplate.
version: 1.4.3
homepage: https://github.com/navaneethkrishnaindeed/pipe_x
repository: https://github.com/navaneethkrishnaindeed/pipe_x
issue_tracker: https://github.com/navaneethkrishnaindeed/pipe_x/issues 

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: 'PipeX Logo'
    path: 'images/pipexlogo.webp'

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

topics:
  - state-management
  - reactive
  - flutter
  - signals
  - controller
